[package]
name = "cower-client"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[dependencies]
cower-common = { path = "../cower-common" }
clap = { version = "4.5.53", features = ["derive"] }
anyhow = "1.0.100"
native-tls = "0.2.14"
