name: Rust CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Add clippy
      run: rustup component add clippy
      
    - name: Install binstall
      uses: cargo-bins/cargo-binstall@main
    
    - name: Install cargo-audit
      run: cargo binstall cargo-audit

    - name: Build the project
      run: cargo build --verbose

    - name: Check warnings with Clippy
      run: cargo clippy --all-targets -- -D warnings --no-deps

    - name: Run tests
      run: cargo test --verbose

    - name: Check for vulnerabilities
      run: cargo audit
